services:
  db:
    image: postgres:18.3
    restart: unless-stopped
    shm_size: 128mbπ
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kasernescenen
    ports:
      - 5432:5432
