name: Kasernescenen CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v5

      - name: Opsæt Bun
        uses: oven-sh/setup-bun@v2

      - name: Installer dependencies
        run: bun install

      - name: Generer Prisma Client
        run: bunx prisma generate

      - name: Lint
        run: bun run lint

      - name: Byg projekt
        run: bun run build
