name: Kasernescenen CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Opsæt Node.js
        uses: oven-sh/setup-bun@v2
        with:
          node-version: '20.x'
          cache: 'bun'

      - name: Installer dependencies
        run: bun install

      - name: Generer Prisma Client
        run: bunx prisma generate

      - name: Lint
        run: bun run lint

      - name: Byg projekt
        run: bun run build
